### ISSUE TITLE
How to install the plugin

### ISSUE THREAD

**Issue by izgzhen** [s92025592025/checkstyle-idea#10]
I can't get onboard with https://github.com/s92025592025/checkstyle-idea/blob/init-result/Notes/InitialResultInstruction.md

**Comment by izgzhen** [comment]
To be precise, you need to tell me how to load your modified local plugin into my local IDE.

> You are require to have IntelliJ IDEA Community Edition 2018 with plugin checkstyle-idea installed. You may reference this page for how to install plugins on IntellJ.

The above text in your original instructions doesn't help. I can't afford the time looking into the IDEA dev manual and figuring out the exact steps.

**Comment by s92025592025** [comment]
updated manual, let us know if there is still anything you don't understand

**Comment by izgzhen** [comment]
@s92025592025 

> and type in checkstyle-idea in the search bar. Then click on the install button of the first search result.

Does it install the "official" checkstyle-idea for me? Shouldn't your modified version be installed?

**Comment by s92025592025** [comment]
The XML parsing part is currently not available to access through GUI. What I am trying to demonstrate here is that our parser and writer can reconstruct the existing XML config even if the config went through our parser and writer. 

The command in the instruction is just parsing and reconstructing the google checkstyle config, and user has to run both config on the original official plugin to see that they both act the same.

**Comment by izgzhen** [comment]
I see, thanks for clarifying this
