### ISSUE TITLE
Proj06 Feedback

### ISSUE THREAD

**Issue by wahleric** [s92025592025/checkstyle-idea#13]
(0/1 pt) The report or the README contains instructions to reproduce the initial results.
Neither the latest version of the report (week 7 as of 2/28/19) or the README contain information about results or how to produce them
(0/3 pts) The initial results are reproducible.
There was no information provided on how to reproduce any results
(0/2 pts) The report has a discussion of the results.
Because this project focus has shifted, there were no results yet to discuss in the latest report
(0/1 pt) The report expands on the methodology and is complete.
This is difficult to gauge. As the project has changed, this report is a re-write, so it does not expand on any previous methodologies.
(1/1 pt) The schedule is updated and there is a reasonable discussion on why it changed.
The schedule has changed from the previous report to reflect the new project focus. The feedback section does discuss the change in the project.
(1/2 pts) The user manual is updated.
The manual appears to be the original Checkstyle-IDEA manual, but with a section added for generating configuration files. Again, this is difficult to gauge as the project has changed, so the old manual is no longer applicable.

In the report, under the “Implementation Plan” section, the description of how users interact with your GUI is a bit confusing. You might want to find a way to break that up somehow into smaller/easier to follow steps by concisely listing what the various buttons do. Also, it’s a bit unclear what freedom users have when defining their own custom rules.

**Comment by s92025592025** [comment]
Sorry, it seemed like we have pushed the week8 report to the root of the repo instead of the week8 folder. Is it possible check that out for us again? Thanks!

**Comment by wahleric** [comment]
I've added the new feedback in another issue

**Comment by s92025592025** [comment]
@wahleric Thanks!
